package com.mbv.ticketsystem.airline.vnair.vniscsoapservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 Generated source
 * version: 2.1
 */
@WebServiceClient(name = "BookingProcess_Service", targetNamespace = "http://muadi.com.vn/", wsdlLocation = "http://webservice.muadi.vn/BookingProcess.asmx?wsdl")
public class BookingProcessService extends Service {

    private final static URL BOOKINGPROCESSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.mbv.ticketsystem.airline.vnair.vniscsoapservice.BookingProcessService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.mbv.ticketsystem.airline.vnair.vniscsoapservice.BookingProcessService.class.getResource(".");
            url = new URL(baseUrl, "http://webservice.muadi.vn/BookingProcess.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://webservice.muadi.vn/BookingProcess.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BOOKINGPROCESSSERVICE_WSDL_LOCATION = url;
    }

    public BookingProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingProcessService() {
        super(BOOKINGPROCESSSERVICE_WSDL_LOCATION, new QName("http://muadi.com.vn/", "BookingProcess_Service"));
    }

    /**
     * @return returns BookingProcessServiceSoap
     */
    @WebEndpoint(name = "BookingProcess_ServiceSoap")
    public BookingProcessServiceSoap getBookingProcessServiceSoap() {
        return super.getPort(new QName("http://muadi.com.vn/", "BookingProcess_ServiceSoap"), BookingProcessServiceSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *                 on the proxy. Supported features not in the
     *                 <code>features</code> parameter will have their default
     *                 values.
     * @return returns BookingProcessServiceSoap
     */
    @WebEndpoint(name = "BookingProcess_ServiceSoap")
    public BookingProcessServiceSoap getBookingProcessServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://muadi.com.vn/", "BookingProcess_ServiceSoap"), BookingProcessServiceSoap.class, features);
    }

    /**
     * @return returns BookingProcessServiceSoap
     */
    @WebEndpoint(name = "BookingProcess_ServiceSoap12")
    public BookingProcessServiceSoap getBookingProcessServiceSoap12() {
        return super.getPort(new QName("http://muadi.com.vn/", "BookingProcess_ServiceSoap12"), BookingProcessServiceSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *                 on the proxy. Supported features not in the
     *                 <code>features</code> parameter will have their default
     *                 values.
     * @return returns BookingProcessServiceSoap
     */
    @WebEndpoint(name = "BookingProcess_ServiceSoap12")
    public BookingProcessServiceSoap getBookingProcessServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://muadi.com.vn/", "BookingProcess_ServiceSoap12"), BookingProcessServiceSoap.class, features);
    }

}
