
package com.mbv.ticketsystem.airline.vnair.vniscsoapservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 */
@WebService(name = "BookingProcess_ServiceSoap", targetNamespace = "http://muadi.com.vn/")

public interface BookingProcessServiceSoap {


    /**
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "ServerStatus", action = "http://muadi.com.vn/ServerStatus")
    @WebResult(name = "ServerStatusResult", targetNamespace = "http://muadi.com.vn/")
    @RequestWrapper(localName = "ServerStatus", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.ServerStatus")
    @ResponseWrapper(localName = "ServerStatusResponse", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.ServerStatusResponse")
    public String serverStatus();

    /**
     * @param hash
     * @param agent
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "AgentLogin", action = "http://muadi.com.vn/AgentLogin")
    @WebResult(name = "AgentLoginResult", targetNamespace = "http://muadi.com.vn/")
    @RequestWrapper(localName = "AgentLogin", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.AgentLogin")
    @ResponseWrapper(localName = "AgentLoginResponse", targetNamespace = "http://muadi.com.vn/")
    public String agentLogin(
            @WebParam(name = "Agent", targetNamespace = "http://muadi.com.vn/")
            String agent,
            @WebParam(name = "Hash", targetNamespace = "http://muadi.com.vn/")
            String hash);

    /**
     * @param tokenKey
     * @param hash
     * @param reservationCode
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "CancelBooking", action = "http://muadi.com.vn/CancelBooking")
    @WebResult(name = "CancelBookingResult", targetNamespace = "http://muadi.com.vn/")
    @RequestWrapper(localName = "CancelBooking", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.CancelBooking")
    @ResponseWrapper(localName = "CancelBookingResponse", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.CancelBookingResponse")
    public String cancelBooking(
            @WebParam(name = "ReservationCode", targetNamespace = "http://muadi.com.vn/")
            String reservationCode,
            @WebParam(name = "TokenKey", targetNamespace = "http://muadi.com.vn/")
            String tokenKey,
            @WebParam(name = "Hash", targetNamespace = "http://muadi.com.vn/")
            String hash);

    /**
     * @param tokenKey
     * @param hash
     * @param reservationCode
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "PaymentBooking", action = "http://muadi.com.vn/PaymentBooking")
    @WebResult(name = "PaymentBookingResult", targetNamespace = "http://muadi.com.vn/")
    @RequestWrapper(localName = "PaymentBooking", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.PaymentBooking")
    @ResponseWrapper(localName = "PaymentBookingResponse", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.PaymentBookingResponse")
    public String paymentBooking(
            @WebParam(name = "ReservationCode", targetNamespace = "http://muadi.com.vn/")
            String reservationCode,
            @WebParam(name = "TokenKey", targetNamespace = "http://muadi.com.vn/")
            String tokenKey,
            @WebParam(name = "Hash", targetNamespace = "http://muadi.com.vn/")
            String hash);

    /**
     * @param tokenKey
     * @param orderID
     * @param hash
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "BookingInfo", action = "http://muadi.com.vn/BookingInfo")
    @WebResult(name = "BookingInfoResult", targetNamespace = "http://muadi.com.vn/")
    @RequestWrapper(localName = "BookingInfo", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.BookingInfo")
    @ResponseWrapper(localName = "BookingInfoResponse", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.BookingInfoResponse")
    public String bookingInfo(
            @WebParam(name = "OrderID", targetNamespace = "http://muadi.com.vn/")
            long orderID,
            @WebParam(name = "TokenKey", targetNamespace = "http://muadi.com.vn/")
            String tokenKey,
            @WebParam(name = "Hash", targetNamespace = "http://muadi.com.vn/")
            String hash);

    /**
     * @param inputData
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "MD5Encrypt", action = "http://muadi.com.vn/MD5Encrypt")
    @WebResult(name = "MD5EncryptResult", targetNamespace = "http://muadi.com.vn/")
    @RequestWrapper(localName = "MD5Encrypt", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.MD5Encrypt")
    @ResponseWrapper(localName = "MD5EncryptResponse", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.MD5EncryptResponse")
    public String md5Encrypt(
            @WebParam(name = "InputData", targetNamespace = "http://muadi.com.vn/")
            String inputData);

    /**
     * @param errorNumber
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GetErrorDescription", action = "http://muadi.com.vn/GetErrorDescription")
    @WebResult(name = "GetErrorDescriptionResult", targetNamespace = "http://muadi.com.vn/")
    @RequestWrapper(localName = "GetErrorDescription", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.GetErrorDescription")
    @ResponseWrapper(localName = "GetErrorDescriptionResponse", targetNamespace = "http://muadi.com.vn/", className = "com.mbv.ticketsystem.airline.vnair.vniscsoap.GetErrorDescriptionResponse")
    public String getErrorDescription(
            @WebParam(name = "ErrorNumber", targetNamespace = "http://muadi.com.vn/")
            int errorNumber);

}
