package com.mbv.ticketsystem.common.airline;

public enum AirTicketingStatus {
    //PENDING, BOOKED, BUYONLY, BOOK_ERROR, EXPIRED, BUYING, PAID, BUY_ERROR, VOID, UNKNOWN, ERROR
    BOOK_PENDING,
    BOOK_PROCESSING,
    BOOK_SUCCESS,
    BOOK_ERROR,
    BOOK_CANCELED,
    BUY_ONLY,
    BUY_PENDING,
    BUY_PROCESSING,
    BUY_SUCCESS,
    BUY_ERROR,
    UNKNOWN
}
